### ISSUE TITLE
great project

### ISSUE THREAD

**Issue by Nitsuya** [Demon000/web-auto#192]
This project is too crazy, covering almost all the protocol.

Windows development environment, there are many errors in NPM Install.

I want to try using VirtualDisplay to rewrite the protocol on Android.

(:

**Comment by Demon000** [comment]
Hi. I don't support windows.

**Comment by Nitsuya** [comment]
Thanks, I'll follow this project~!!

**Comment by Nitsuya** [comment]
hi, developer, is this an AA client project or AA server project ?

**Comment by Nitsuya** [comment]
Thank you authors for your open source contributions
